# Generated by Django 2.2.3 on 2020-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_tool_image'),
        ('EPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epp',
            name='tools',
            field=models.ManyToManyField(to='tool.Tool'),
        ),
    ]
