# Generated by Django 2.2.3 on 2020-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0002_epp_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='tools',
            field=models.ManyToManyField(blank=True, to='tool.Tool'),
        ),
    ]
