# Generated by Django 2.2.3 on 2020-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0003_auto_20200224_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='epp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='epp/'),
        ),
    ]
