# Generated by Django 2.2.3 on 2020-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0004_epp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eppmedia/'),
        ),
    ]
