# Generated by Django 2.2.3 on 2020-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200213_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
