# Generated by Django 2.2.3 on 2020-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_tool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(default='', upload_to='tool/'),
            preserve_default=False,
        ),
    ]
