# Generated by Django 2.2.3 on 2020-03-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_tool_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='slug',
        ),
    ]
