# Generated by Django 2.2.3 on 2020-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20200320_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toolmedia/'),
        ),
    ]
